# Generated by Django 5.1 on 2024-08-21 15:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='message',
            field=models.TextField(blank=True, verbose_name='Reminder Message'),
        ),
        migrations.AddField(
            model_name='reminder',
            name='reminder_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Reminder Date'),
        ),
    ]
